---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests/approval
  - certificatesigningrequests/status
  verbs:
  - update
- apiGroups:
  - certificates.k8s.io
  resourceNames:
  - battery.liquidmetal-x.dev/flintlockd-client
  - battery.liquidmetal-x.dev/flintlockd-serving
  resources:
  - signers
  verbs:
  - approve
  - sign
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manager-role
  namespace: system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
- apiGroups:
  - ""
  resourceNames:
  - flintlockd-ca
  resources:
  - configmaps
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resourceNames:
  - flintlockd-client-ca
  - flintlockd-serving-ca
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
