---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - battery.liquidmetal-x.dev
  resources:
  - microvmclaims
  - pools
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - battery.liquidmetal-x.dev
  resources:
  - microvmclaims/finalizers
  - pools/finalizers
  verbs:
  - update
- apiGroups:
  - battery.liquidmetal-x.dev
  resources:
  - microvmclaims/status
  - pools/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests/approval
  - certificatesigningrequests/status
  verbs:
  - update
- apiGroups:
  - certificates.k8s.io
  resourceNames:
  - battery.liquidmetal-x.dev/exec-agent-serving
  - battery.liquidmetal-x.dev/flintlockd-client
  - battery.liquidmetal-x.dev/flintlockd-serving
  resources:
  - signers
  verbs:
  - approve
  - sign
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manager-role
  namespace: system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
- apiGroups:
  - ""
  resourceNames:
  - battery-operator-battery-config
  resources:
  - configmaps
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resourceNames:
  - flintlockd-ca
  resources:
  - configmaps
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resourceNames:
  - host-address-pins
  resources:
  - configmaps
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resourceNames:
  - battery-flintlockd-client
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resourceNames:
  - flintlockd-client-ca
  - flintlockd-serving-ca
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
