apiVersion: v1
kind: ServiceAccount
metadata:
  name: battery-operator-exec-agent
  namespace: battery-operator-system
  labels:
    app.kubernetes.io/name: battery-operator
    app.kubernetes.io/component: exec-agent
    app.kubernetes.io/managed-by: kustomize
