/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Command exec-agent is the Exec Agent (docs/requirements/05-exec-agent.md),
// which config/exec-agent runs on every Host. It is not a controller
// manager, so it was written by hand rather than generated by kubebuilder.
package main

import (
	"context"
	"flag"
	"os"
	"os/signal"
	"strings"
	"syscall"
	"time"

	"k8s.io/client-go/dynamic"
	"k8s.io/client-go/kubernetes"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/log/zap"

	"github.com/phoban01/battery-operator/internal/execagent"
	"github.com/phoban01/battery-operator/internal/hostcheck"
)

// claimResync is the full resync period of the Exec Agent's claim cache.
const claimResync = 10 * time.Minute

func main() {
	var cfg execagent.Config
	var audiences string
	flag.StringVar(&cfg.HostNode, "host-node", os.Getenv("NODE_NAME"),
		"The name of this Host's Node. Defaults to $NODE_NAME, which the DaemonSet sets from the downward API.")
	flag.StringVar(&cfg.Flintlockd, "flintlockd", "",
		"The endpoint of this Host's flintlockd, an IP address of this Host and a port.")
	flag.StringVar(&cfg.FlintlockdTLS.CertFile, "flintlockd-cert-file", "",
		"The client certificate the agent presents to flintlockd.")
	flag.StringVar(&cfg.FlintlockdTLS.KeyFile, "flintlockd-key-file", "", "The key of --flintlockd-cert-file.")
	flag.StringVar(&cfg.FlintlockdTLS.CAFile, "flintlockd-ca-file", "",
		"The CA that signed flintlockd's serving certificate.")
	flag.StringVar(&cfg.Address, "address", "",
		"The address to serve the exec API on. Empty is the Host's internal address, read from its Node.")
	flag.IntVar(&cfg.Port, "port", execagent.DefaultPort, "The port of the exec API.")
	flag.StringVar(&cfg.TLS.CertFile, "tls-cert-file", "",
		"The exec API's serving certificate, which has to name the address it is served on.")
	flag.StringVar(&cfg.TLS.KeyFile, "tls-key-file", "", "The key of --tls-cert-file.")
	flag.StringVar(&audiences, "token-audiences", "",
		"Comma-separated audiences a caller's token has to carry. Empty accepts the API server's own.")
	flag.DurationVar(&cfg.ExecOpenTimeout, "exec-open-timeout", execagent.DefaultExecOpenTimeout,
		"How long flintlockd has to open the exec stream of a request.")
	flag.DurationVar(&cfg.CallTimeout, "call-timeout", execagent.DefaultCallTimeout,
		"The deadline of every unary call to flintlockd and every TokenReview.")
	flag.StringVar(&cfg.NotReadyDir, "not-ready-dir", hostcheck.DefaultNotReadyDir,
		"The directory the Host Image writes its not ready reasons to.")
	flag.StringVar(&cfg.KVMDevice, "kvm-device", hostcheck.DefaultKVMDevice,
		"The path of the Host's KVM device node, which has to be a character device.")
	flag.StringVar(&cfg.KVMSysfsDir, "kvm-sysfs-dir", hostcheck.DefaultKVMSysfsDir,
		"Where sysfs lists the KVM device, which has to be there.")
	flag.StringVar(&cfg.ThinPool, "thin-pool", hostcheck.DefaultThinPool,
		"The device-mapper name of containerd's thin pool, containerd's devmapper pool_name.")
	flag.StringVar(&cfg.SysBlockDir, "sys-block-dir", hostcheck.DefaultSysBlockDir,
		"sysfs's directory of block devices, where the thin pool is looked for.")
	flag.DurationVar(&cfg.DrainTimeout, "drain-timeout", execagent.DefaultDrainTimeout,
		"How long Bound claims hold a drain of the Host's Node open.")
	flag.StringVar(&cfg.Guard.Namespace, "guard-namespace", os.Getenv("POD_NAMESPACE"),
		"The namespace of the drain guard pod. Defaults to $POD_NAMESPACE, the agent's own.")
	flag.StringVar(&cfg.Guard.Image, "guard-image", execagent.DefaultGuardImage, "The image of the drain guard pod.")
	flag.DurationVar(&cfg.SyncInterval, "sync-interval", execagent.DefaultSyncInterval,
		"How often the Node report and the drain guard are reconciled.")
	opts := zap.Options{}
	opts.BindFlags(flag.CommandLine)
	flag.Parse()
	for a := range strings.SplitSeq(audiences, ",") {
		if a = strings.TrimSpace(a); a != "" {
			cfg.TokenAudiences = append(cfg.TokenAudiences, a)
		}
	}
	cfg.ApplyDefaults()

	log := zap.New(zap.UseFlagOptions(&opts))
	ctrl.SetLogger(log)
	setupLog := log.WithName("setup")
	fail := func(err error, msg string, keysAndValues ...any) {
		setupLog.Error(err, msg, keysAndValues...)
		os.Exit(1)
	}

	hostAddrs, err := hostcheck.HostAddresses()
	if err != nil {
		fail(err, "Failed to list the Host's addresses")
	}
	if err := cfg.Validate(hostAddrs); err != nil {
		fail(err, "Refused to start with an invalid configuration")
	}
	restConfig, err := ctrl.GetConfig()
	if err != nil {
		fail(err, "Failed to load the Kubernetes client configuration")
	}
	kube, err := kubernetes.NewForConfig(restConfig)
	if err != nil {
		fail(err, "Failed to build the Kubernetes client")
	}
	dyn, err := dynamic.NewForConfig(restConfig)
	if err != nil {
		fail(err, "Failed to build the Kubernetes client")
	}

	ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
	defer stop()

	// Run refuses to start unless the agent's identity names its Host
	// (EA-050).
	fl, err := execagent.DialFlintlockd(cfg.Flintlockd, cfg.FlintlockdTLS, hostAddrs)
	if err != nil {
		fail(err, "Failed to connect to flintlockd", "endpoint", cfg.Flintlockd)
	}
	defer func() { _ = fl.Close() }()

	res := execagent.ProvisionalClaimResource
	res.Group, res.Version, res.Resource = cfg.Claims.Group, cfg.Claims.Version, cfg.Claims.Resource
	claims := execagent.NewDynamicClaims(dyn, res, claimResync)
	go claims.Run(ctx)

	err = execagent.Run(ctx, execagent.Options{
		Config: &cfg, Kube: kube, Claims: claims, Flintlockd: fl, HostAddresses: hostAddrs,
		Logger: log.WithName("exec-agent"),
	})
	if err != nil && ctx.Err() == nil {
		fail(err, "Stopped the Exec Agent")
	}
}
