/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Command exec-agent is the Exec Agent (docs/requirements/05-exec-agent.md),
// which config/exec-agent runs on every Host. It is not a controller
// manager, so it was written by hand rather than generated by kubebuilder.
package main

import (
	"context"
	"flag"
	"os"
	"os/signal"
	"strings"
	"syscall"
	"time"

	"k8s.io/client-go/kubernetes"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/log/zap"

	"github.com/phoban01/battery-operator/internal/execagent"
	"github.com/phoban01/battery-operator/internal/hostcert"
	"github.com/phoban01/battery-operator/internal/hostcheck"
)

// claimResync is the full resync period of the Exec Agent's claim cache.
const claimResync = 10 * time.Minute

func main() {
	var cfg execagent.Config
	var audiences string
	flag.StringVar(&cfg.HostNode, "host-node", os.Getenv("NODE_NAME"),
		"The name of this Host's Node. Defaults to $NODE_NAME, which the DaemonSet sets from the downward API.")
	flag.StringVar(&cfg.Flintlockd, "flintlockd", "",
		"The endpoint of this Host's flintlockd, an IP address of this Host and a port.")
	flag.StringVar(&cfg.Address, "address", "",
		"The address to serve the exec API on. Empty is the Host's internal address, read from its Node.")
	flag.IntVar(&cfg.Port, "port", execagent.DefaultPort, "The port of the exec API.")
	flag.StringVar(&cfg.TrustDomain, "trust-domain", os.Getenv("TRUST_DOMAIN"),
		"The SPIFFE trust domain of the Host's certificates, the Operator's. Defaults to $TRUST_DOMAIN. Required.")
	flag.StringVar(&cfg.FlintlockdCertDir, "flintlockd-cert-dir", execagent.DefaultFlintlockdCertDir,
		"The Host directory the agent writes flintlockd's serving certificate, its key and the client CA bundle to.")
	flag.StringVar(&cfg.CABundle.Namespace, "ca-bundle-namespace", os.Getenv("POD_NAMESPACE"),
		"The Operator's namespace, where it publishes its CA certificates. Defaults to $POD_NAMESPACE, the agent's own.")
	flag.StringVar(&cfg.CABundle.Name, "ca-bundle-configmap", hostcert.CABundleConfigMap,
		"The ConfigMap in which the Operator publishes its CA certificates.")
	flag.DurationVar(&cfg.CertificateDuration, "certificate-duration", 0,
		"The validity to ask for in each certificate request. Zero leaves it to the Operator.")
	flag.StringVar(&audiences, "token-audiences", "",
		"Comma-separated audiences a caller's token has to carry. Empty is "+execagent.DefaultTokenAudience+".")
	flag.DurationVar(&cfg.ExecOpenTimeout, "exec-open-timeout", execagent.DefaultExecOpenTimeout,
		"How long flintlockd has to open the exec stream of a request.")
	flag.DurationVar(&cfg.CallTimeout, "call-timeout", execagent.DefaultCallTimeout,
		"The deadline of every unary call to flintlockd and every TokenReview.")
	flag.StringVar(&cfg.NotReadyDir, "not-ready-dir", hostcheck.DefaultNotReadyDir,
		"The directory the Host Image writes its not ready reasons to.")
	flag.StringVar(&cfg.KVMDevice, "kvm-device", hostcheck.DefaultKVMDevice,
		"The path of the Host's KVM device node, which has to be a character device.")
	flag.StringVar(&cfg.KVMSysfsDir, "kvm-sysfs-dir", hostcheck.DefaultKVMSysfsDir,
		"Where sysfs lists the KVM device, which has to be there.")
	flag.StringVar(&cfg.ThinPool, "thin-pool", hostcheck.DefaultThinPool,
		"The device-mapper name of containerd's thin pool, containerd's devmapper pool_name.")
	flag.StringVar(&cfg.SysBlockDir, "sys-block-dir", hostcheck.DefaultSysBlockDir,
		"sysfs's directory of block devices, where the thin pool is looked for.")
	flag.DurationVar(&cfg.DrainTimeout, "drain-timeout", execagent.DefaultDrainTimeout,
		"How long Bound claims hold a drain of the Host's Node open.")
	flag.StringVar(&cfg.Guard.Namespace, "guard-namespace", os.Getenv("POD_NAMESPACE"),
		"The namespace of the drain guard pod. Defaults to $POD_NAMESPACE, the agent's own.")
	flag.StringVar(&cfg.Guard.Image, "guard-image", execagent.DefaultGuardImage, "The image of the drain guard pod.")
	flag.DurationVar(&cfg.SyncInterval, "sync-interval", execagent.DefaultSyncInterval,
		"How often the Node report and the drain guard are reconciled.")
	opts := zap.Options{}
	opts.BindFlags(flag.CommandLine)
	flag.Parse()
	for a := range strings.SplitSeq(audiences, ",") {
		if a = strings.TrimSpace(a); a != "" {
			cfg.TokenAudiences = append(cfg.TokenAudiences, a)
		}
	}
	cfg.ApplyDefaults()

	log := zap.New(zap.UseFlagOptions(&opts))
	ctrl.SetLogger(log)
	setupLog := log.WithName("setup")
	fail := func(err error, msg string, keysAndValues ...any) {
		setupLog.Error(err, msg, keysAndValues...)
		os.Exit(1)
	}

	hostAddrs, err := hostcheck.HostAddresses()
	if err != nil {
		fail(err, "Failed to list the Host's addresses")
	}
	if err := cfg.Validate(hostAddrs); err != nil {
		fail(err, "Refused to start with an invalid configuration")
	}
	restConfig, err := ctrl.GetConfig()
	if err != nil {
		fail(err, "Failed to load the Kubernetes client configuration")
	}
	kube, err := kubernetes.NewForConfig(restConfig)
	if err != nil {
		fail(err, "Failed to build the Kubernetes client")
	}

	ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
	defer stop()

	// Run refuses to start unless the agent's identity names its Host
	// (EA-050).
	// Run obtains the certificates before it serves; the connection to
	// flintlockd is made once they are there.
	certs := execagent.NewCertificates(kube, &cfg, nil)
	fl, err := execagent.DialFlintlockd(cfg.Flintlockd, certs, hostAddrs)
	if err != nil {
		fail(err, "Failed to connect to flintlockd", "endpoint", cfg.Flintlockd)
	}
	defer func() { _ = fl.Close() }()

	claims, err := execagent.NewKubeClaims(ctx, restConfig, claimResync)
	if err != nil {
		fail(err, "Failed to build the claim lookup")
	}
	go func() {
		if err := claims.Run(ctx); err != nil && ctx.Err() == nil {
			fail(err, "Stopped reading the claims")
		}
	}()

	err = execagent.Run(ctx, execagent.Options{
		Config: &cfg, Kube: kube, Claims: claims, Flintlockd: fl, Certificates: certs, HostAddresses: hostAddrs,
		Logger: log.WithName("exec-agent"),
	})
	if err != nil && ctx.Err() == nil {
		fail(err, "Stopped the Exec Agent")
	}
}
