//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostReference) DeepCopyInto(out *HostReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostReference.
func (in *HostReference) DeepCopy() *HostReference {
	if in == nil {
		return nil
	}
	out := new(HostReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MicroVMClaim) DeepCopyInto(out *MicroVMClaim) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MicroVMClaim.
func (in *MicroVMClaim) DeepCopy() *MicroVMClaim {
	if in == nil {
		return nil
	}
	out := new(MicroVMClaim)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MicroVMClaim) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MicroVMClaimList) DeepCopyInto(out *MicroVMClaimList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MicroVMClaim, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MicroVMClaimList.
func (in *MicroVMClaimList) DeepCopy() *MicroVMClaimList {
	if in == nil {
		return nil
	}
	out := new(MicroVMClaimList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MicroVMClaimList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MicroVMClaimSpec) DeepCopyInto(out *MicroVMClaimSpec) {
	*out = *in
	out.PoolRef = in.PoolRef
	if in.RenewTime != nil {
		in, out := &in.RenewTime, &out.RenewTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MicroVMClaimSpec.
func (in *MicroVMClaimSpec) DeepCopy() *MicroVMClaimSpec {
	if in == nil {
		return nil
	}
	out := new(MicroVMClaimSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MicroVMClaimStatus) DeepCopyInto(out *MicroVMClaimStatus) {
	*out = *in
	if in.MicroVM != nil {
		in, out := &in.MicroVM, &out.MicroVM
		*out = new(MicroVMReference)
		**out = **in
	}
	if in.Host != nil {
		in, out := &in.Host, &out.Host
		*out = new(HostReference)
		**out = **in
	}
	if in.BoundTime != nil {
		in, out := &in.BoundTime, &out.BoundTime
		*out = (*in).DeepCopy()
	}
	if in.LeaseExpiresAt != nil {
		in, out := &in.LeaseExpiresAt, &out.LeaseExpiresAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MicroVMClaimStatus.
func (in *MicroVMClaimStatus) DeepCopy() *MicroVMClaimStatus {
	if in == nil {
		return nil
	}
	out := new(MicroVMClaimStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MicroVMReference) DeepCopyInto(out *MicroVMReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MicroVMReference.
func (in *MicroVMReference) DeepCopy() *MicroVMReference {
	if in == nil {
		return nil
	}
	out := new(MicroVMReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoolReference) DeepCopyInto(out *PoolReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoolReference.
func (in *PoolReference) DeepCopy() *PoolReference {
	if in == nil {
		return nil
	}
	out := new(PoolReference)
	in.DeepCopyInto(out)
	return out
}
